version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET="ankurkumar"
      - MONGO_URI="mongodb+srv://ankurq:root@cluster0.agtfzis.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    ports:
      - '3000:3000'
